# Site Configuration
title: anish lakkapragada
tagline: math, statistics, and machine learning @ yale
description: >-
  Anish Lakkapragada — Yale CS + Math. Research at CVPR, NeurIPS, AAAI.
url: https://anishlk.com
baseurl: ""

lang: en
timezone: America/Los_Angeles
permalink: pretty

github:
  username: anish-lakkapragada

twitter:
  username: _anishlk

social:
  name: Anish Lakkapragada
  email: anish.lakkapragada@yale.edu
  links:
    - https://github.com/anish-lakkapragada
    - https://twitter.com/_anishlk
    - https://unsplash.com/@anishlk

avatar: /assets/img/anish.png
social_preview_image: /assets/img/anish.png

# Build
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

include:
  - assets/sae/encoder
  - assets/sae/mnist_digits.json

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
  - twitter-strategy.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 10
