version: "3.8"
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.3
    build: .
    # Uncomment these if you are having permission issues
    # build:
    #   args:
    #     GROUPID: # id -g
    #     GROUPNAME: # id -gn
    #     USERID: # id -u
    #     USERNAME: # echo $USER
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    develop:
      watch:
        - path: .
          action: sync
          target: /srv/jekyll
          ignore:
            - .git/
            - _site/
        - path: .
          action: rebuild
